### ISSUE TITLE
Consider adding a license to the code

### ISSUE THREAD

**Issue by flowpoint** [aredden/flux-fp8-api#12]
Consider adding a license to this repo, so people can use the code appropiately.
Friendly reminder to fix also the broken link in the readme, if you do.

This would also be useful/applicable to your dependencies like: https://github.com/aredden/torch-cublas-hgemm

**Comment by aredden** [comment]
Good idea! I'll do that now.

**Comment by flowpoint** [comment]
https://github.com/aredden/flux-fp8-api/blob/3cc2f3f2f85a6d11840575da54a7829ebfe4d2ca/README.md?plain=1#L48

**Comment by aredden** [comment]
Oh! I didn't even realize that haha 😨

**Comment by flowpoint** [comment]
Thanks for fixing this. 
If you also add an open license to  https://github.com/aredden/torch-cublas-hgemm the project is free to use.
