### ISSUE TITLE
No issue - just a thank you!

### ISSUE THREAD

**Issue by ashakoen** [aredden/flux-fp8-api#4]
I've been learning a lot by getting this project up and running on a lower-end GPU. I've had no major issues, and I already have the LoRA loading working. Just wanted to say thanks!!

**Comment by aredden** [comment]
You're welcome! :)

**Comment by emcmanus** [comment]
@aredden Kudos! There's a definite need for an open source, performance-oriented (non-interactive) inference server for production use.

This is a very hackable codebase and performance really is 2x other solutions – thank you!
